export const theme = {
  light: {
    primaryDark: '',
    primaryMedium: '',
    primaryLight: '',
    background: '',
    hyperLink: '',
    buttonBgDark: '',
    buttonBgMedium: '',
    buttonBgLight: '',
    fontDark: '',
    fontMedium: '',
    fontLight: '',
    white: '',
    black: '',
    contrastDark: '',
    contrastMedium: '',
    contrastLight: '',
  },
  dark: {
    primaryDark: '',
    primaryMedium: '',
    primaryLight: '',
    background: '',
    hyperLink: '',
    buttonBgDark: '',
    buttonBgMedium: '',
    buttonBgLight: '',
    fontDark: '',
    fontMedium: '',
    fontLight: '',
    white: '',
    black: '',
    contrastDark: '',
    contrastMedium: '',
    contrastLight: '',
  }
};